### ISSUE TITLE
Some environment variables not taken into account

### ISSUE THREAD

**Issue by joancafom** [bitnami/bitnami-docker-nginx-ldap-auth-daemon#3]
Some environment variables are not taken into account when executing the daemon (e.g. `NGINXLDAP_LDAP_BIND_PASSWORD`) This leads to malfunctioning and incorrect handling of legit requests. In order to reproduce this problem, you can follow these steps:

1) Create a basic setup with `NGINX`, `NGINX-LDAP-Auth-Daemon` and `OpenLDAP`. The following `docker-compose.yaml` was based on the `README.md` instructions:

```bash
$ mkdir app

$ cat << EOF > app/index.html
<html>
<body>
<h1>Hello world!.</h1>
</body>
</html>
EOF

$ mkdir conf

$ cat << EOF > conf/ldap_nginx.conf
    server {
      listen 0.0.0.0:8080;

      location = / {
         auth_request /auth-proxy;
      }

      location = /auth-proxy {
         internal;

         proxy_pass http://nginx-ldap:8888;
      }
   }
```

```yaml
version: '2'
services:
  nginx-ldap:
    image: 'docker.io/bitnami/nginx-ldap-auth-daemon:0-debian-10'
    ports:
      - 8888:8888
    environment:
      - NGINXLDAP_PORT_NUMBER=8888
      - NGINXLDAP_LDAP_URI=ldap://openldap:1389
      - NGINXLDAP_LDAP_BASE_DN=dc=example,dc=org
      - NGINXLDAP_LDAP_BIND_DN=cn=admin,dc=example,dc=org
      - NGINXLDAP_LDAP_BIND_PASSWORD=adminpassword
  openldap:
    image: docker.io/bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
  nginx:
    image: 'docker.io/bitnami/nginx:latest'
    ports:
      - '8080:8080'
    volumes:
      - './conf/ldap_nginx.conf:/opt/bitnami/nginx/conf/server_blocks/ldap_nginx.conf'
      - './app:/app'
    depends_on:
      - openldap
      - nginx-ldap

```

Notice that `conf/ldap_nginx.conf` **does not explicitly set any LDAP directive** (unlike the `README.md`), as `NGINX-LDAP-Auth-Daemon` is fully **configured using env. variables**. If no LDAP directive is set in the server block, the daemon should use the ones provided in the env. vars, [as stated in the documentation](https://github.com/bitnami/bitnami-docker-nginx-ldap-auth-daemon#configuration).

2. Navigate to http://localhost:8080 and introduce correct credentials. The authentication fails as shown in the `OpenLDAP` logs:

```bash
nginx_1       | 172.22.0.1 - - [21/Dec/2020:20:52:13 +0000] "GET / HTTP/1.1" 401 172 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0"
openldap_1    | 5fe10b03 conn=1000 fd=15 ACCEPT from IP=172.22.0.2:52444 (IP=0.0.0.0:1389)
openldap_1    | 5fe10b03 conn=1000 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
openldap_1    | 5fe10b03 conn=1000 op=0 RESULT tag=97 err=49 text=
```
Note: `err=49` denotes Invalid Credentials ([https://www.openldap.org/lists/openldap-technical/201012/msg00175.html](example))

3. As a consequence, the resource is not accessible by legitimate users:

![Screenshot 2020-12-22 at 20 09 16](https://user-images.githubusercontent.com/24253844/102924303-93781800-4491-11eb-9c95-ae88db23c0cf.png)
