### ISSUE TITLE
Internal Server Error when trying to authenticate

### ISSUE THREAD

**Issue by kevn-gonz** [bitnami/bitnami-docker-nginx-ldap-auth-daemon#5]
Hi guys,
Not sure if this is a problem at my end, if I misunderstood something or what, but I've been struggling with setting up LDAP auth.

_Here are some details:_
1. Right now I'm using a laptop with Windows 10 - Docker Desktop
2. I'm connected using VPN to my company network -> Where LDS is located
3. docker-compose version 1.29.0, build 07737305

_Here are the details of the problem I hope you can help me with:_
For testing purposes, before implementing bitnami/nginx-LDAP authentication in my final docker-compose.yml file I have downloaded yours. The only change I made was to remove the **openldap service**, as I plan to use my company's LDS.
In the ldap_nginx.conf file I changed the corresponding info, it looks like this:

      location = /auth-proxy {
         internal;
         proxy_pass http://nginx-ldap:8888;
         proxy_set_header X-Ldap-URL "ldap://mycompanyserver:port";
         proxy_set_header X-Ldap-BaseDN "OU=****,DC=****,DC=****,DC=****,DC=****";
         proxy_set_header X-Ldap-BindDN "CN=****,OU=****,DC=****,DC=****,DC=****,DC=****";
         proxy_set_header X-Ldap-BindPass "****";
      }

Of course I have to remove the password, account, url, etc, info, but you got my point.. When I access http://localhost:8080 it asks me to login, once I enter my user information it keeps loading and loading and at the end shows me an "Internal Server Error" page... 
I tested this without VPN to see if it was even reaching my LDS server and once I disconnected the VPN, it didn't even care about what credential I entered, it kept asking for credentials..., so it seems to me that it is in fact reaching my LDS server but when the response is received it does nothing? possibly? Here is where I'm stuck...

Appreciate any advice/help from your side!
Thank you

**Comment by alemorcuq** [comment]
Hi, @kevn-gonz/

Can you share your `docker-compose.yml` file and your `ldap_nginx.conf` file? Remember to remove any sensitive data before sharing them. 

Also, please check that you are not missing any configuration needed by your LDAP service: https://github.com/bitnami/bitnami-docker-nginx-ldap-auth-daemon#configuration

**Comment by kevn-gonz** [comment]
Hi @alemorcuq thanks for looking into this!
My configuration is very straight forward, here it is:

**docker-compose.yml:**
```
version: '2'

services:
  nginx-ldap:
    image: bitnami/nginx-ldap-auth-daemon
    ports:
      - 8888:8888
  nginx:
    image: bitnami/nginx
    ports:
     - 8080:8080
    volumes:
     - ./conf/ldap_nginx.conf:/opt/bitnami/nginx/conf/server_blocks/ldap_nginx.conf
#  openldap:
#    image: bitnami/openldap
#    ports:
#      - '1389:1389'
#      - '1636:1636'
#    environment:
#      - LDAP_ADMIN_USERNAME=admin
#      - LDAP_ADMIN_PASSWORD=adminpassword
#      - LDAP_USERS=customuser
#      - LDAP_PASSWORDS=custompassword
```

**ldap_nginx.conf:**
```
server {
      listen 0.0.0.0:8080;

      location = / {
         auth_request /auth-proxy;
         proxy_pass https://google.com;
      }

      location = /auth-proxy {
         internal;

         proxy_pass http://nginx-ldap:8888;

         proxy_set_header X-Ldap-URL "ldap://hostname:port";
         proxy_set_header X-Ldap-BaseDN "OU=,DC=,DC=,DC=,DC=";
         proxy_set_header X-Ldap-BindDN "CN=,OU=,DC=,DC=,DC=,DC=";
         proxy_set_header X-Ldap-BindPass "";

#         proxy_set_header X-Ldap-URL "ldap://openldap:1389";
#         proxy_set_header X-Ldap-BaseDN "dc=example,dc=org";
#         proxy_set_header X-Ldap-BindDN "cn=admin,dc=example,dc=org";
#         proxy_set_header X-Ldap-BindPass "adminpassword";
      }
   }
```

If you want to test it, just uncomment the lines I commented and comment, or remove the lines related to my company's LDAP.
At the end, once you successfully authenticate using  customuser:custompassword  it will take you to google, not a big deal tho, but I can't make it work with my company's LDAP authentication.
Thanks!
