### ISSUE TITLE
Daemon prompts LDAP server numerous times per session, initiating a multi-factor verification each time

### ISSUE THREAD

**Issue by miltoncs** [bitnami/bitnami-docker-nginx-ldap-auth-daemon#8]
**Description**

My company has an ldap server that I wanted to interface with to create a developer app that we could all login to. Now, this ldap server also kicks off a MFA challenge whenever a user is authenticated. We used the same ldap server and bind user for other dev applications (e.g. Nexus), and had no issues. In this case, with the proxy in place, a user can login, but many MFA challenges are issued (between 4 and 10 depending on the action). Also, more MFA challenges are issued for every action the user does, even after authenticating and reaching the website.

Both the proxy and the developer app are running in Kubernetes (via AWS EKS) version 1.19.

**Steps to reproduce the issue:**

1. Templates for `bitnami-docker-nginx-ldap-auth-daemon`:
```
---
# Source: nginx-ldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap
spec:
  ports:
    - name: "8888"
      port: 8888
---
# Source: nginx-ldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap
spec:
  ports:
    - name: "8888"
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    name: nginx-ldap
---
# Source: nginx-ldap/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ldap
  template:
    metadata:
      labels:
        name: nginx-ldap
---
# Source: nginx-ldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap
spec:
  ports:
    - name: "8888"
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    name: nginx-ldap
---
# Source: nginx-ldap/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ldap
  template:
    metadata:
      labels:
        name: nginx-ldap
    spec:
      containers:
        - image: "bitnami/nginx-ldap-auth-daemon:0.20200116.0-debian-10-r480"
          env:
          - name: "NGINXLDAP_HTTP_COOKIE_NAME"
            value: "nginx_ldap_auth"
          - name: "NGINXLDAP_HTTP_REALM"
            value: "Internal"
          - name: "NGINXLDAP_LDAP_BASE_DN"
            value: "dc=***,dc=****,dc=****"
          - name: "NGINXLDAP_LDAP_BIND_DN"
            value: "uid=******,dc=*****,dc=*****,dc=*****"
          - name: "NGINXLDAP_LDAP_BIND_PASSWORD"
            value: "**********"
          - name: "NGINXLDAP_LDAP_FILTER"
            value: "(uid=%(username)s)"
          - name: "NGINXLDAP_LDAP_URI"
            value: "ldaps://*****"
          imagePullPolicy: Always
          name: nginx-ldap
          ports:
            - containerPort: 8888
              protocol: TCP
---
# Source: nginx-ldap/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ldap-proxy
spec:
  rules:
  - host: "app.host.com"
    http:
      paths:
      - path: "/auth-proxy"
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-ldap
            port:
              number: 8888
  tls:
  - hosts:
    - app.host.com
    secretName: ssl-certs
```
2. Ingress.yaml for app which needs auth:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-app-site
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://app.host.com/auth-proxy
spec:
  tls:
    - hosts:
        - "app.host.com"
      secretName: ssl-certs
  rules:
    - host: "app.host.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: RELEASE-NAME-app-site
              servicePort: 8080
```

**Describe the results you received:**

The user is given the username/password prompt by the browser, correct credentials initiate numerous MFA challenges, after all the MFA challenges are completed, the website appears.

**Describe the results you expected:**

One MFA challenge should allow the session to go uninterrupted. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The observed behavior is consistent.

**Version**

Kubernetes (via AWS EKS) version 1.19. Nothing is run locally.

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 66
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.938GiB
 Name: docker-desktop
 ID: UARS:JVG2:F4FM:3YIH:ASPG:ZTJI:GMVU:QDTK:QBFG:AYZV:TLYF:ERL4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 45
  System Time: 2021-10-13T13:05:06.2017973Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

The bitnami daemon is deployed to a namespace using a Helm chart. The app is deployed to a different namespace using its own Helm chart. The Kubernetes cluster is an EKS cluster in AWS.

I'm not using a .conf file to configure the daemon, only the environment variables.
